### PR TITLE
CLS command implementation

### PR DESCRIPTION
**Pull request by Luca1991**
This PR implements the CLS command that, like in the original SoftICE, clears the commands/logs window.

Tested using a Windows 11 Pro VM (VMWare)

### CODE REVIEW

**Comment by vitoplantamura** [comment]
Hi Luca,

thank you for your PR :-)

Just two things:

1) In LogWnd::Clear, you should set "allocSize = 0;".

"allocSize" is used in LogWnd::AddString to keep the size of the log window text in check.

2) can you update README.md adding CLS under "Implemented Commands"?

Thank you, --vito

**Comment by Luca1991** [comment]
Hi Vito, I've fixed both issues.
I also added a call to Home() in LogWnd::Clear (just found this issue when testing).

**Comment by vitoplantamura** [comment]
yes, you are right!

Just one last thing I noticed when reviewing the changes:

Can you replace "contents.clear();" with "eastl::vector<eastl::string >().swap(contents);"?

We must be sure that the vector's memory is actually freed, and "vector::clear" doesn't guarantee that...

Thank you, --vito

**Comment by Luca1991** [comment]
Fixed!
Sorry for this mistake, I'm not a C++ wizard as you can see (which on the other hand is a good thing, because I can learn a lot more from this project!)

Of topic: do you plan to create something to keep communication easy for contributors? Like a slack/discord channel? I have some suggestions related to the build system that I'd like to discuss.

**Comment by vitoplantamura** [comment]
It's not a mistake :-) The requirement to free the memory, let's say, deterministically, is a very particular requirement of the LogWnd implementation :-)

For the collaboration tool, we will talk about it soon, I promise :-)

Thank you, --vito

**Pull request merged**
